theme: jekyll-theme-minimal
title: [Table Reading & Understanding in Documents Images]
description: [A python-based software to transform unstructured data to structured data]
logo: [https://www.google.com/url?sa=i&url=https%3A%2F%2Flawtomated.com%2Fstructured-data-vs-unstructured-data-what-are-they-and-why-care%2F&psig=AOvVaw3hf2HhQ9Te1NJwL7Vrukdu&ust=1617140898469000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJj6lbm91u8CFQAAAAAdAAAAABAD]
